---
- hosts: live_env
  connection: local
  gather_facts: true
  become: true

  tasks:
  - name: Sync app_files
    synchronize:
      src: /home/ubuntu/"app_files"
      dest: /home/ubuntu/

  - name: Sync Downloads
    synchronize:
      src: /home/ubuntu/Downloads
      dest: /home/ubuntu/

  - name: Update sources lsit
    apt:
      update_cache: yes

  - name: Install python dependencies
    apt:
      name:
        - python3
        - python-pip
        - python3-pip
      state: present

  - name: install requirements.txt
    shell: pip install -r "app_files"/requirements.txt
# pip install -r requirements.txt
# Copy over ssh key