---
- hosts: local
  connection: local
  gather_facts: true
  become: true

  tasks:
  - name: Sync App_Files
    synchronize:
      src: /home/ubuntu/App Files
      dest: /home/ubuntu/

  - name: Update sources lsit
    apt:
      update_cache: yes

  - name: Install python dependencies
    apt:
      name:
        - python3
        - python-pip
        - python3-pip
      state: present

  - name: install requirements.txt
    shell: pip install -r "App Files"/requirements.txt
# pip install -r requirements.txt
# Copy over ssh key